name: Spanish Tuition Wellington
markdown: redcarpet
highlighter: pygments

navigation:
- text: Home
  url: /
  alias_url: /index.html
- text: About Me
  url: /about_me.html
- text: About learning Spanish
  url: /about_spanish.html
- text: About Translating & Interpreting
  url: /about_translating.html
